#!/bin/sh


# ----------------------------------------------------------------------------
readonly SETUP=${0##*/}
readonly APPLICATION='name'
readonly PREREQUISITES='bash'
# ----------------------------------------------------------------------------


# run as root -->
if [ "$USER" != 'root' ]; then
  [ "$LOGNAME" != 'root' ] && echo "please run as root" && exit 1
fi
# run as root <--


# setup functions -->
setup_usage () {
  rc=0
  [ -n "${*}" ] && echo "${*}" && rc=1
  echo "\
Usage:
  $SETUP [install | uninstall]"

  exit $rc
}

setup_check_prerequisites () {
  for cmd in $PREREQUISITES; do
    command -v $cmd >/dev/null
    [ $? -ne 0 ] && echo "you need the '$cmd' command" && exit 1
  done
}

setup_install () {
  echo "install"
}

setup_uninstall () {
  echo "uninstall"
}
# setup functions <--


# parse cli -->
case $1 in
  help) setup_usage ;;
  install)
    setup_check_prerequisites
    setup_install ;;
  uninstall) setup_uninstall ;;
  *) setup_usage 'invalid or missing argument' ;;
esac
# parse cli <--


exit 0
