#!/bin/sh


# run as root -->
if [ "$USER" != 'root' ]; then
  [ "$LOGNAME" != 'root' ] && echo "Please run as root" && exit 1
fi
# run as root <--


# setup functions -->
setup_usage () {
  rc=0
  [ -n "${*}" ] && echo "${*}" && rc=1
  echo "\
Usage:
  ${0##*/} [install | uninstall]"

  exit $rc
}

setup_install () {
  echo "install"
}

setup_uninstall () {
  echo "uninstall"
}
# setup functions <--


# parse cli -->
case $1 in
  help)      setup_usage     ;;
  install)   setup_install   ;;
  uninstall) setup_uninstall ;;
  *)         setup_usage 'invalid or missing argument' ;;
esac
# parse cli <--


exit 0
